version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      # Inicializa o banco de dados com os scripts que tem na pasta /init
      - ./mysql/init:/docker-entrypoint-initdb.d
      - node-people-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbpeople
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - node-people-network

  app:
    build:
      context: ./app-people
      dockerfile: Dockerfile
    image: leticiapillar/desafio-nginx-node-app:latest
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh npm start
    tty: true
    volumes:
      - ./app-people:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - node-people-network
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: leticiapillar/desafio-nginx:latest
    container_name: nginx
    restart: always
    networks:
      - node-people-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - app

networks:
  node-people-network:
    driver: bridge

volumes:
  node-people-data: {}
